# Data Description
**Age**: The age of the individual in years.
Gender: The gender of the individual, categorized as male or female.
Profession: The occupation or profession of the individual.
Marital_status: The marital status of the individual, such as married &, single
Education: The educational qualification of the individual Graduate and Post Graduate
No_of_Dependents: The number of dependents (e.g., children, elderly parents) that the individual supports financially.
Personal_loan: A binary variable indicating whether the individual has taken a personal loan "Yes" or "No"
House_loan: A binary variable indicating whether the individual has taken a housing loan "Yes" or "No"
Partner_working: A binary variable indicating whether the individual's partner is employed "Yes" or "No"
Salary: The individual's salary or income.
Partner_salary: The salary or income of the individual's partner, if applicable.
Total_salary: The total combined salary of the individual and their partner (if applicable).
Price: The price of a product or service.
Make: The type of automobile

In [1]:
# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd

# Libraries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# to restrict the float value to 3 decimal places
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [4]:
!ls .

AUSTO.ipynb          austo_automobile.csv

In [14]:
data = pd.read_csv('austo_automobile.csv',na_values=['missing','inf','nan'])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1581 non-null   int64
 1   Gender            1528 non-null   object
 2   Profession        1581 non-null   object
 3   Marital_status    1581 non-null   object
 4   Education         1581 non-null   object
 5   No_of_Dependents  1581 non-null   int64
 6   Personal_loan     1581 non-null   object
 7   House_loan        1581 non-null   object
 8   Partner_working   1581 non-null   object
 9   Salary            1581 non-null   int64
 10  Partner_salary    1475 non-null   float64
 11  Total_salary      1581 non-null   int64
 12  Price             1581 non-null   int64
 13  Make              1581 non-null   object
dtypes: float64(1), int64(5), object(8)
memory usage: 173.1+ KB

In [15]:
data.isnull().sum()

Age                   0
Gender               53
Profession            0
Marital_status        0
Education             0
No_of_Dependents      0
Personal_loan         0
House_loan            0
Partner_working       0
Salary                0
Partner_salary      106
Total_salary          0
Price                 0
Make                  0
dtype: int64

In [19]:
data['Profession'].unique()

array(['Business', 'Salaried'], dtype=object)

In [20]:
data['Marital_status'].unique()

array(['Married', 'Single'], dtype=object)

In [33]:
data['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [30]:
data['Gender']=data['Gender'].map(lambda x : 'Female' if x in ["Femal", "Female", "Femle"] else x)

In [32]:
# data.shape[0] will give us the number of rows in the dataset
# selecting the instances where missing value is greater than 0
pd.DataFrame({'Count':data.isnull().sum()[data.isnull().sum()>0],'Percentage':(data.isnull().sum()[data.isnull().sum()>0]/data.shape[0])*100})

                Count  Percentage
Gender             53       3.352
Partner_salary    106       6.705

In [71]:
data.shape

(1581, 14)

In [70]:
gdata=data[data['Gender'].isnull()==True]
pd.DataFrame({'Count':gdata.count(),'Percentage':(gdata.count()/data.shape[0])*100})

                  Count  Percentage
Age                  53       3.352
Gender                0       0.000
Profession           53       3.352
Marital_status       53       3.352
Education            53       3.352
No_of_Dependents     53       3.352
Personal_loan        53       3.352
House_loan           53       3.352
Partner_working      53       3.352
Salary               53       3.352
Partner_salary       50       3.163
Total_salary         53       3.352
Price                53       3.352
Make                 53       3.352

In [60]:
data[data['Gender'].isnull()==True]['Education'].value_counts(normalize=True,dropna=False)

Education
Post Graduate   0.642
Graduate        0.358
Name: proportion, dtype: float64

In [52]:
data[data['Gender'].isnull()==True]['Make'].value_counts(normalize=True,dropna=False)

Make
Sedan       0.849
SUV         0.113
Hatchback   0.038
Name: proportion, dtype: float64

In [34]:
data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Age,1581.000,NaN,NaN,NaN,31.922,8.426,22.000,25.000,29.000,38.000,54.000
Gender,1528,2,Male,1199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Profession,1581,2,Salaried,896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Marital_status,1581,2,Married,1443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,1581,2,Post Graduate,985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
No_of_Dependents,1581.000,NaN,NaN,NaN,2.458,0.943,0.000,2.000,2.000,3.000,4.000
Personal_loan,1581,2,Yes,792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
House_loan,1581,2,No,1054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Partner_working,1581,2,Yes,868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Salary,1581.000,NaN,NaN,NaN,60392.220,14674.825,30000.000,51900.000,59500.000,71800.000,99300.000
Partner_salary,1475.000,NaN,NaN,NaN,20225.559,19573.149,0.000,0.000,25600.000,38300.000,80500.000
Total_salary,1581.000,NaN,NaN,NaN,79625.996,25545.858,30000.000,60500.000,78000.000,95900.000,171000.000
Price,1581.000,NaN,NaN,NaN,35597.723,13633.637,18000.000,25000.000,31000.000,47000.000,70000.000
Make,1581,3,Sedan,702,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.head()

,Age,Gender,Profession,Marital_status,Education,No_of_Dependents,Personal_loan,House_loan,Partner_working,Salary,Partner_salary,Total_salary,Price,Make
0,53,Male,Business,Married,Post Graduate,4,No,No,Yes,99300,70700.000,170000,61000,SUV
1,53,Femal,Salaried,Married,Post Graduate,4,Yes,No,Yes,95500,70300.000,165800,61000,SUV
2,53,Female,Salaried,Married,Post Graduate,3,No,No,Yes,97300,60700.000,158000,57000,SUV
3,53,Female,Salaried,Married,Graduate,2,Yes,No,Yes,72500,70300.000,142800,61000,SUV
4,53,Male,Salaried,Married,Post Graduate,3,No,No,Yes,79700,60200.000,139900,57000,SUV